"""AI runtime foundation models

Revision ID: 0035_ai_runtime
Revises: 0034_production_auth
Create Date: 2026-08-13 06:36:42.111447
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0035_ai_runtime"
down_revision: str | None = "0034_production_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_providers",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("provider_identity", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("availability_state", sa.String(length=30), nullable=False),
        sa.Column("provider_version", sa.String(length=100), nullable=False),
        sa.Column("cost_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_providers_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_providers")),
        sa.UniqueConstraint(
            "organization_id", "provider_identity", name=op.f("uq_ai_providers_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_ai_providers_organization_id"), "ai_providers", ["organization_id"], unique=False
    )
    op.create_table(
        "prompt_purposes",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owning_domain", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_prompt_purposes_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_purposes")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_prompt_purposes_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_prompt_purposes_organization_id"),
        "prompt_purposes",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "ai_model_capabilities",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("model_identity", sa.String(length=200), nullable=False),
        sa.Column("capability_type", sa.String(length=40), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("cost_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_model_capabilities_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
            name=op.f("fk_ai_model_capabilities_provider_id_ai_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_model_capabilities")),
        sa.UniqueConstraint(
            "organization_id",
            "provider_id",
            "model_identity",
            "capability_type",
            name=op.f("uq_ai_model_capabilities_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_ai_model_capabilities_organization_id"),
        "ai_model_capabilities",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_model_capabilities_provider_id"),
        "ai_model_capabilities",
        ["provider_id"],
        unique=False,
    )
    op.create_table(
        "prompt_templates",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("purpose_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_prompt_templates_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_prompt_templates_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["purpose_id"],
            ["prompt_purposes.id"],
            name=op.f("fk_prompt_templates_purpose_id_prompt_purposes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_templates")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_prompt_templates_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_prompt_templates_organization_id"),
        "prompt_templates",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_templates_owner_id"), "prompt_templates", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_templates_purpose_id"), "prompt_templates", ["purpose_id"], unique=False
    )
    op.create_table(
        "ai_requests",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=200), nullable=False),
        sa.Column("context_type", sa.String(length=100), nullable=False),
        sa.Column("context_reference", sa.String(length=500), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=True),
        sa.Column("approval_request_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("output_classification", sa.String(length=30), nullable=True),
        sa.Column("output_metadata", sa.JSON(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["approval_requests.id"],
            name=op.f("fk_ai_requests_approval_request_id_approval_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["ai_model_capabilities.id"],
            name=op.f("fk_ai_requests_capability_id_ai_model_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_requests_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name=op.f("fk_ai_requests_requester_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_requests")),
    )
    op.create_index(
        op.f("ix_ai_requests_approval_request_id"),
        "ai_requests",
        ["approval_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_requests_capability_id"), "ai_requests", ["capability_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_requests_organization_id"), "ai_requests", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_requests_requester_id"), "ai_requests", ["requester_id"], unique=False
    )
    op.create_table(
        "prompt_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("prompt_content", sa.Text(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_prompt_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_prompt_versions_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["prompt_templates.id"],
            name=op.f("fk_prompt_versions_template_id_prompt_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint(
            "template_id", "version_number", name=op.f("uq_prompt_versions_template_id")
        ),
    )
    op.create_index(
        op.f("ix_prompt_versions_created_by"), "prompt_versions", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_versions_organization_id"),
        "prompt_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_versions_template_id"), "prompt_versions", ["template_id"], unique=False
    )
    op.create_table(
        "ai_cost_observations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("usage_quantity", sa.Numeric(precision=19, scale=6), nullable=False),
        sa.Column("usage_unit", sa.String(length=50), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=19, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("related_request_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "estimated_cost >= 0",
            name=op.f("ck_ai_cost_observations_ai_estimated_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "usage_quantity >= 0",
            name=op.f("ck_ai_cost_observations_ai_usage_quantity_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["ai_model_capabilities.id"],
            name=op.f("fk_ai_cost_observations_capability_id_ai_model_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_cost_observations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_ai_cost_observations_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ai_providers.id"],
            name=op.f("fk_ai_cost_observations_provider_id_ai_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["related_request_id"],
            ["ai_requests.id"],
            name=op.f("fk_ai_cost_observations_related_request_id_ai_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_cost_observations")),
    )
    op.create_index(
        op.f("ix_ai_cost_observations_capability_id"),
        "ai_cost_observations",
        ["capability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_cost_observations_organization_id"),
        "ai_cost_observations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_cost_observations_project_id"),
        "ai_cost_observations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_cost_observations_provider_id"),
        "ai_cost_observations",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_cost_observations_related_request_id"),
        "ai_cost_observations",
        ["related_request_id"],
        unique=False,
    )
    op.create_table(
        "prompt_evaluations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=False),
        sa.Column("evaluator_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100",
            name=op.f("ck_prompt_evaluations_prompt_evaluation_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluator_id"], ["users.id"], name=op.f("fk_prompt_evaluations_evaluator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_prompt_evaluations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_prompt_evaluations_prompt_version_id_prompt_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_evaluations")),
    )
    op.create_index(
        op.f("ix_prompt_evaluations_evaluator_id"),
        "prompt_evaluations",
        ["evaluator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_evaluations_organization_id"),
        "prompt_evaluations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_evaluations_prompt_version_id"),
        "prompt_evaluations",
        ["prompt_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_evaluations_prompt_version_id"), table_name="prompt_evaluations")
    op.drop_index(op.f("ix_prompt_evaluations_organization_id"), table_name="prompt_evaluations")
    op.drop_index(op.f("ix_prompt_evaluations_evaluator_id"), table_name="prompt_evaluations")
    op.drop_table("prompt_evaluations")
    op.drop_index(
        op.f("ix_ai_cost_observations_related_request_id"), table_name="ai_cost_observations"
    )
    op.drop_index(op.f("ix_ai_cost_observations_provider_id"), table_name="ai_cost_observations")
    op.drop_index(op.f("ix_ai_cost_observations_project_id"), table_name="ai_cost_observations")
    op.drop_index(
        op.f("ix_ai_cost_observations_organization_id"), table_name="ai_cost_observations"
    )
    op.drop_index(op.f("ix_ai_cost_observations_capability_id"), table_name="ai_cost_observations")
    op.drop_table("ai_cost_observations")
    op.drop_index(op.f("ix_prompt_versions_template_id"), table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_organization_id"), table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_created_by"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    op.drop_index(op.f("ix_ai_requests_requester_id"), table_name="ai_requests")
    op.drop_index(op.f("ix_ai_requests_organization_id"), table_name="ai_requests")
    op.drop_index(op.f("ix_ai_requests_capability_id"), table_name="ai_requests")
    op.drop_index(op.f("ix_ai_requests_approval_request_id"), table_name="ai_requests")
    op.drop_table("ai_requests")
    op.drop_index(op.f("ix_prompt_templates_purpose_id"), table_name="prompt_templates")
    op.drop_index(op.f("ix_prompt_templates_owner_id"), table_name="prompt_templates")
    op.drop_index(op.f("ix_prompt_templates_organization_id"), table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_index(op.f("ix_ai_model_capabilities_provider_id"), table_name="ai_model_capabilities")
    op.drop_index(
        op.f("ix_ai_model_capabilities_organization_id"), table_name="ai_model_capabilities"
    )
    op.drop_table("ai_model_capabilities")
    op.drop_index(op.f("ix_prompt_purposes_organization_id"), table_name="prompt_purposes")
    op.drop_table("prompt_purposes")
    op.drop_index(op.f("ix_ai_providers_organization_id"), table_name="ai_providers")
    op.drop_table("ai_providers")
    # ### end Alembic commands ###
