"""external intelligence connector foundation

Revision ID: 0036_external_connectors
Revises: 0035_ai_runtime
Create Date: 2026-08-13 07:29:50.900981
"""

import hashlib
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0036_external_connectors"
down_revision: str | None = "0035_ai_runtime"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "market_connector_definitions",
        sa.Column(
            "capability",
            sa.String(length=80),
            nullable=False,
            server_default="read_evidence",
        ),
    )
    op.add_column(
        "market_connector_definitions",
        sa.Column(
            "authentication_state",
            sa.String(length=30),
            nullable=False,
            server_default="not_configured",
        ),
    )
    op.add_column(
        "market_connector_definitions",
        sa.Column("credential_reference", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "market_connector_definitions",
        sa.Column("rate_limit_metadata", sa.JSON(), nullable=False, server_default="{}"),
    )
    with op.batch_alter_table("market_connector_definitions") as batch:
        batch.create_unique_constraint(
            "uq_market_connector_definitions_name", ["organization_id", "name"]
        )
    op.add_column(
        "market_data_records", sa.Column("payload_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "market_data_records", sa.Column("idempotency_key", sa.String(length=200), nullable=True)
    )
    records = sa.table(
        "market_data_records",
        sa.column("id", sa.Uuid()),
        sa.column("source_id", sa.Uuid()),
        sa.column("payload_hash", sa.String()),
        sa.column("idempotency_key", sa.String()),
    )
    connection = op.get_bind()
    for row in connection.execute(sa.select(records.c.id, records.c.source_id)).mappings():
        legacy = f"{row['id']}:{row['source_id']}"
        connection.execute(
            records.update()
            .where(records.c.id == row["id"])
            .values(
                payload_hash=hashlib.sha256(legacy.encode()).hexdigest(),
                idempotency_key=f"legacy:{row['id']}",
            )
        )
    op.alter_column("market_data_records", "payload_hash", nullable=False)
    op.alter_column("market_data_records", "idempotency_key", nullable=False)
    op.create_index(
        op.f("ix_market_data_records_payload_hash"),
        "market_data_records",
        ["payload_hash"],
        unique=False,
    )
    with op.batch_alter_table("market_data_records") as batch:
        batch.create_unique_constraint(
            "uq_market_data_records_payload_hash",
            ["organization_id", "source_id", "payload_hash"],
        )
        batch.create_unique_constraint(
            "uq_market_data_records_idempotency",
            ["organization_id", "source_id", "idempotency_key"],
        )
    if connection.dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION prevent_market_data_record_mutation() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'Raw external evidence is immutable';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER market_data_records_immutable
            BEFORE UPDATE OR DELETE ON market_data_records
            FOR EACH ROW EXECUTE FUNCTION prevent_market_data_record_mutation()
            """
        )
    op.add_column(
        "market_ingestion_jobs",
        sa.Column("errors", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "normalized_market_items",
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "normalized_market_items", sa.Column("language", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "normalized_market_items",
        sa.Column("relevance_metadata", sa.JSON(), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("normalized_market_items", "relevance_metadata")
    op.drop_column("normalized_market_items", "language")
    op.drop_column("normalized_market_items", "occurred_at")
    op.drop_column("market_ingestion_jobs", "errors")
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER market_data_records_immutable ON market_data_records")
        op.execute("DROP FUNCTION prevent_market_data_record_mutation()")
    with op.batch_alter_table("market_data_records") as batch:
        batch.drop_constraint("uq_market_data_records_idempotency", type_="unique")
        batch.drop_constraint("uq_market_data_records_payload_hash", type_="unique")
    op.drop_index(op.f("ix_market_data_records_payload_hash"), table_name="market_data_records")
    op.drop_column("market_data_records", "idempotency_key")
    op.drop_column("market_data_records", "payload_hash")
    with op.batch_alter_table("market_connector_definitions") as batch:
        batch.drop_constraint("uq_market_connector_definitions_name", type_="unique")
    op.drop_column("market_connector_definitions", "rate_limit_metadata")
    op.drop_column("market_connector_definitions", "credential_reference")
    op.drop_column("market_connector_definitions", "authentication_state")
    op.drop_column("market_connector_definitions", "capability")
    # ### end Alembic commands ###
