import type { Diagnosis, Evidence, Gift, GrowthOpportunity, GrowthProspect, ResearchRun } from "../lib/api/growth";
import { createGrowthDiagnosis, createGrowthGift, createGrowthOpportunity, createGrowthOutreach } from "../app/growth/actions";
import { EvidencePicker } from "./EvidencePicker";
import { GrowthActionForm } from "./GrowthActionForm";

type Props={experimentId:string;prospect:GrowthProspect;evidence:Evidence[];opportunities:GrowthOpportunity[];diagnoses:Diagnosis[];gifts:Gift[];runs:ResearchRun[]};
export function GrowthArtifactForms({experimentId,prospect,evidence,opportunities,diagnoses,gifts,runs}:Props){
  const hidden=<><input type="hidden" name="experiment_id" value={experimentId}/><input type="hidden" name="prospect_id" value={prospect.id}/></>;
  const approvedGifts=gifts.filter(x=>["approved","ready_for_delivery","delivered"].includes(x.status));
  const provenanceRuns=runs.filter(x=>x.ai_request_id&&x.status==="completed");
  return <div className="artifact-forms guided-composer">
    <details id="diagnosis"><summary><span>1</span> Compose opportunity and diagnosis</summary><div className="composer-help">Use only selected evidence. Put unknown facts in “missing information,” never in a guessed score.</div>
      <GrowthActionForm action={createGrowthOpportunity} label="Save opportunity analysis">{hidden}<EvidencePicker evidence={evidence}/><label>Opportunity type<select name="opportunity_type"><option value="website_conversion">Website conversion</option><option value="seo">Search visibility</option><option value="google_business">Google Business</option><option value="other">Other</option></select></label><label>Observed problem<textarea name="problem_statement" required/></label><label>Customer impact<textarea name="customer_impact" required/></label><label>Recommended offer<textarea name="recommended_offer" required/></label><label>Confidence<input name="confidence" type="number" min="0" max="1" step="0.05" defaultValue="0.6"/></label><label>Risks (one per line)<textarea name="risks"/></label><label>Missing information<textarea name="missing_information"/></label></GrowthActionForm>
      <GrowthActionForm action={createGrowthDiagnosis} label="Save Growth diagnosis" variant="secondary">{hidden}<EvidencePicker evidence={evidence}/><label>Business situation<textarea name="business_situation" required/></label><label>Growth problems (one per line)<textarea name="growth_problems" required/></label><label>Customer impact<textarea name="customer_impact" required/></label><label>Recommended improvements<textarea name="recommended_improvements" required/></label><label>Confidence<input name="confidence" type="number" min="0" max="1" step="0.05" defaultValue="0.6"/></label><label>Risks<textarea name="risks"/></label></GrowthActionForm>
    </details>
    {opportunities.length&&diagnoses.length?<details id="growth-gift"><summary><span>2</span> Build the customer-specific Growth Gift</summary><div className="composer-help">Translate the diagnosis into a useful before/after concept. This creates a draft only.</div><GrowthActionForm action={createGrowthGift} label="Create Gift draft">{hidden}<EvidencePicker evidence={evidence}/><label>Opportunity<select name="opportunity_id">{opportunities.map(x=><option value={x.id} key={x.id}>{x.problem_statement}</option>)}</select></label><label>Diagnosis<select name="diagnosis_id">{diagnoses.map(x=><option value={x.id} key={x.id}>{x.business_situation}</option>)}</select></label>{[["title","Gift title"],["description","What the Gift contains"],["before_state","Observed before state"],["after_state","Proposed after concept"],["observed_issue","Specific observed issue"],["recommended_improvement","Recommended improvement"],["expected_value","Expected value (not guaranteed ROI)"],["customer_rationale","Why this matters to this customer"],["personalized_diagnosis","Personalized diagnosis"],["implementation_scope","Possible implementation scope"],["customer_value_explanation","Customer value explanation"]].map(([name,label])=><label key={name}>{label}<textarea name={name} required/></label>)}</GrowthActionForm></details>:null}
    {approvedGifts.length?<details id="outreach"><summary><span>3</span> Prepare founder outreach</summary>{provenanceRuns.length?<GrowthActionForm action={createGrowthOutreach} label="Create outreach draft">{hidden}<EvidencePicker evidence={evidence}/><label>Approved Gift<select name="gift_id">{approvedGifts.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><label>Diagnosis<select name="diagnosis_id"><option value="">None</option>{diagnoses.map(x=><option value={x.id} key={x.id}>{x.business_situation}</option>)}</select></label><label>Research provenance<select name="ai_request_id">{provenanceRuns.map((x,i)=><option value={x.ai_request_id!} key={x.id}>Completed governed research {i+1}</option>)}</select></label><label>Channel<select name="channel"><option value="email">Email</option><option value="instagram_dm">Instagram DM</option><option value="linkedin">LinkedIn</option></select></label>{[["subject","Subject"],["opening_sentence","Specific opening"],["personalized_context","Customer context"],["problem_observation","Evidence-backed observation"],["gift_explanation","Useful Gift explanation"],["soft_cta","Low-pressure next step"],["body","Complete draft"]].map(([name,label])=><label key={name}>{label}<textarea name={name} required/></label>)}</GrowthActionForm>:<p className="inline-alert">A completed governed research run is required as outreach provenance. Configure AI and complete research, or continue the evidence review without outreach.</p>}</details>:null}
  </div>;
}
