import type { Diagnosis, Evidence, Gift, GrowthOpportunity, GrowthProspect, ResearchRun } from "../lib/api/growth";
import { createGrowthDiagnosis, createGrowthGift, createGrowthOpportunity, createGrowthOutreach } from "../app/growth/actions";
import { GrowthActionForm } from "./GrowthActionForm";

export function GrowthArtifactForms({experimentId,prospects,evidence,opportunities,diagnoses,gifts,runs}:{experimentId:string;prospects:GrowthProspect[];evidence:Evidence[];opportunities:GrowthOpportunity[];diagnoses:Diagnosis[];gifts:Gift[];runs:ResearchRun[]}){
  if(!prospects.length)return null;
  const shared=<>{<input type="hidden" name="experiment_id" value={experimentId}/>}<label>Prospect<select name="prospect_id">{prospects.map(x=><option value={x.id} key={x.id}>{x.business_name}</option>)}</select></label><label>Evidence IDs (comma separated)<input name="evidence_ids" required placeholder={evidence.map(x=>x.id).slice(0,2).join(", ")}/></label></>;
  return <div className="artifact-forms">
    <details><summary>Create opportunity analysis</summary><GrowthActionForm action={createGrowthOpportunity} label="Save analysis">{shared}<label>Type<select name="opportunity_type"><option value="website_conversion">Website conversion</option><option value="seo">SEO</option><option value="google_business">Google Business</option><option value="other">Other</option></select></label><label>Observed problem<textarea name="problem_statement" required/></label><label>Customer impact<textarea name="customer_impact" required/></label><label>Recommended offer<textarea name="recommended_offer" required/></label><label>Confidence<input name="confidence" type="number" min="0" max="1" step="0.05" defaultValue="0.6"/></label><label>Risks (one per line)<textarea name="risks"/></label><label>Missing information<textarea name="missing_information"/></label></GrowthActionForm></details>
    <details><summary>Create diagnosis</summary><GrowthActionForm action={createGrowthDiagnosis} label="Save diagnosis">{shared}<label>Business situation<textarea name="business_situation" required/></label><label>Growth problems (one per line)<textarea name="growth_problems" required/></label><label>Customer impact<textarea name="customer_impact" required/></label><label>Recommended improvements<textarea name="recommended_improvements" required/></label><label>Confidence<input name="confidence" type="number" min="0" max="1" step="0.05" defaultValue="0.6"/></label><label>Risks<textarea name="risks"/></label></GrowthActionForm></details>
    {opportunities.length&&diagnoses.length?<details><summary>Create Growth Gift</summary><GrowthActionForm action={createGrowthGift} label="Create Gift draft">{shared}<label>Opportunity<select name="opportunity_id">{opportunities.map(x=><option value={x.id} key={x.id}>{x.problem_statement}</option>)}</select></label><label>Diagnosis<select name="diagnosis_id">{diagnoses.map(x=><option value={x.id} key={x.id}>{x.business_situation}</option>)}</select></label>{["title","description","before_state","after_state","observed_issue","recommended_improvement","expected_value","customer_rationale","personalized_diagnosis","implementation_scope","customer_value_explanation"].map(x=><label key={x}>{x.replaceAll("_"," ")}<textarea name={x} required/></label>)}</GrowthActionForm></details>:null}
    {gifts.some(x=>["approved","ready_for_delivery","delivered"].includes(x.status))?<details><summary>Create outreach draft</summary><GrowthActionForm action={createGrowthOutreach} label="Create outreach draft">{shared}<label>Approved Gift<select name="gift_id">{gifts.filter(x=>["approved","ready_for_delivery","delivered"].includes(x.status)).map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><label>Diagnosis<select name="diagnosis_id"><option value="">None</option>{diagnoses.map(x=><option value={x.id} key={x.id}>{x.business_situation}</option>)}</select></label><label>Governed AI request<select name="ai_request_id">{runs.filter(x=>x.ai_request_id).map(x=><option value={x.ai_request_id!} key={x.id}>{x.id}</option>)}</select></label><label>Channel<select name="channel"><option value="email">Email</option><option value="instagram_dm">Instagram DM</option><option value="linkedin">LinkedIn</option></select></label>{["subject","opening_sentence","personalized_context","problem_observation","gift_explanation","soft_cta","body"].map(x=><label key={x}>{x.replaceAll("_"," ")}<textarea name={x} required/></label>)}</GrowthActionForm></details>:null}
  </div>;
}
