import Link from "next/link";
import type { ApiResult } from "../lib/api/types";
import type { DemandDashboard, DemandEvidence, DemandSignal, MarketCluster, MarketEvidence, MarketSignal, MarketSource, SignalOpportunityProjection } from "../lib/api/commerce-intelligence";

const pct=(value:number)=>`${Math.round(value*100)}%`;
const label=(value:string)=>value.replaceAll("_"," ");
function Failed({message}:{message:string}){return <div className="dashboard-state compact state-error"><strong>Section unavailable</strong><span>{message}</span></div>}

export function MarketIntelligenceWorkspace({sources,signals,evidence,clusters,demandSignals,demandEvidence,dashboard}:{sources:ApiResult<MarketSource[]>;signals:ApiResult<MarketSignal[]>;evidence:ApiResult<MarketEvidence[]>;clusters:ApiResult<MarketCluster[]>;demandSignals:ApiResult<DemandSignal[]>;demandEvidence:ApiResult<DemandEvidence[]>;dashboard:ApiResult<DemandDashboard>}){
 const signalRows=signals.ok?signals.data:[], evidenceRows=evidence.ok?evidence.data:[], demandRows=demandSignals.ok?demandSignals.data:[];
 const evidenceCoverage=signalRows.length?Math.round(signalRows.filter((signal)=>evidenceRows.some((item)=>item.signal_id===signal.id)).length/signalRows.length*100):0;
 return <div className="commerce-workspace">
  <section className="page-heading"><div><p className="eyebrow">Observe → substantiate → interpret</p><h1>Market Intelligence</h1><p className="page-description">A persisted evidence workspace. Signals describe what was observed; demand records aggregate evidence but never create products or decisions.</p></div><div className="live-contract"><span>Source of truth</span><strong>Intelligence APIs</strong></div></section>
  <section className="intelligence-metrics" aria-label="Market intelligence overview"><article><span>Market signals</span><strong>{signalRows.length}</strong><small>{signals.ok?"persisted observations":"unavailable"}</small></article><article><span>Evidence coverage</span><strong>{evidenceCoverage}%</strong><small>signals with linked evidence</small></article><article><span>Demand signals</span><strong>{demandRows.length}</strong><small>{demandRows.filter((row)=>row.status==="approved").length} approved</small></article><article><span>Active sources</span><strong>{sources.ok?sources.data.filter((row)=>row.status==="active").length:"—"}</strong><small>registered sources</small></article></section>
  <div className="commerce-grid commerce-grid-wide"><section className="commerce-panel"><header><div><p className="eyebrow">Signal feed</p><h2>Observed market movement</h2></div><span>{signalRows.length} records</span></header>{!signals.ok?<Failed message={signals.error.message}/>:!signalRows.length?<div className="dashboard-state compact"><strong>No market signals recorded</strong><span>Connect or manually ingest evidence before interpreting demand.</span></div>:<div className="commerce-list">{signalRows.map((signal)=><Link href={`/market-intelligence/${signal.id}`} key={signal.id}><div><strong>{signal.title}</strong><p>{signal.description}</p><small>{signal.region} · {label(signal.signal_type)} · {new Date(signal.observed_at).toLocaleDateString("en-US")}</small></div><aside><b>{pct(signal.confidence_score)}</b><span>{signal.trend_direction}</span></aside></Link>)}</div>}</section>
   <section className="commerce-panel"><header><div><p className="eyebrow">Customer pain & need</p><h2>Demand evidence</h2></div><span>{demandRows.length} records</span></header>{!demandSignals.ok?<Failed message={demandSignals.error.message}/>:!demandRows.length?<div className="dashboard-state compact"><strong>No demand signals recorded</strong></div>:<div className="demand-list">{demandRows.slice(0,8).map((item)=><article key={item.id}><div><span>{label(item.source_type)}</span><b>{item.status}</b></div><h3>{item.problem_statement}</h3><p>“{item.customer_language}”</p><small>{item.customer_segment} · {item.evidence_count} evidence · {pct(item.confidence)}</small></article>)}</div>}</section></div>
  <div className="commerce-grid"><section className="commerce-panel"><header><div><p className="eyebrow">Evidence explorer</p><h2>Source ledger</h2></div></header>{!evidence.ok?<Failed message={evidence.error.message}/>:<div className="evidence-compact">{evidenceRows.slice(0,10).map((item)=><article key={item.id}><span>{label(item.evidence_type)}</span><p>{item.content_reference}</p><strong>{pct(item.strength_score)}</strong></article>)}{!evidenceRows.length&&<div className="dashboard-state compact"><strong>No market evidence recorded</strong></div>}</div>}{demandEvidence.ok&&demandEvidence.data.length>0&&<p className="panel-footnote">Plus {demandEvidence.data.length} demand evidence records retained with source traceability.</p>}</section>
   <section className="commerce-panel"><header><div><p className="eyebrow">Patterns</p><h2>Signal clusters</h2></div></header>{!clusters.ok?<Failed message={clusters.error.message}/>:<div className="cluster-grid">{clusters.data.map((item)=><article key={item.id}><strong>{item.name}</strong><span>{item.category}</span><b>{Math.round(item.impact_score)} impact</b><small>{pct(item.confidence)} confidence</small></article>)}{!clusters.data.length&&<div className="dashboard-state compact"><strong>No clusters recorded</strong></div>}</div>}</section></div>
  <section className="commerce-panel gap-panel"><header><div><p className="eyebrow">Evidence gaps</p><h2>What the system still does not know</h2></div></header>{!dashboard.ok?<Failed message={dashboard.error.message}/>:<div className="gap-grid"><article><strong>{dashboard.data.predictive_indicators.length}</strong><span>predictive indicators</span><p>Predictions remain supporting evidence, never guarantees.</p></article><article><strong>{signalRows.length-evidenceRows.reduce((count,row,index,all)=>count+(all.findIndex((x)=>x.signal_id===row.signal_id)===index?1:0),0)}</strong><span>signals without linked evidence</span><p>Add source references before relying on these observations.</p></article><article><strong>{demandRows.filter((row)=>row.status!=="approved").length}</strong><span>unapproved demand signals</span><p>Human review is required before downstream use.</p></article></div>}</section>
 </div>;
}

export function MarketSignalDetail({signal,evidence,sources,opportunities}:{signal:MarketSignal;evidence:ApiResult<MarketEvidence[]>;sources:ApiResult<MarketSource[]>;opportunities:ApiResult<SignalOpportunityProjection[]>}){
 const source=sources.ok?sources.data.find((item)=>item.id===signal.source_id):undefined;
 const rows=evidence.ok?evidence.data.filter((item)=>item.signal_id===signal.id):[];
 return <div className="commerce-workspace"><Link className="back-link" href="/market-intelligence">← Market Intelligence</Link><section className="commerce-hero"><div><p className="eyebrow">{signal.category} · {signal.region}</p><h1>{signal.title}</h1><p>{signal.description}</p><div className="opportunity-tags"><span>{label(signal.signal_type)}</span><span>{signal.trend_direction}</span><span>{signal.status}</span></div></div><aside><span>Observed confidence</span><strong>{pct(signal.confidence_score)}</strong><small>{source?.name??"Source record unavailable"}</small></aside></section><section className="commerce-panel"><header><div><p className="eyebrow">Evidence chain</p><h2>Why this signal exists</h2></div><span>{rows.length} records</span></header>{!evidence.ok?<Failed message={evidence.error.message}/>:!rows.length?<div className="dashboard-state compact"><strong>No linked evidence</strong><span>This signal must not be treated as substantiated.</span></div>:<div className="evidence-compact">{rows.map((item)=><article key={item.id}><span>{label(item.evidence_type)}</span><p>{item.content_reference}</p><strong>{pct(item.strength_score)}</strong></article>)}</div>}</section><section className="commerce-panel"><header><div><p className="eyebrow">Opportunity traceability</p><h2>Where this evidence is used</h2></div></header>{!opportunities.ok?<Failed message={opportunities.error.message}/>:!opportunities.data.length?<div className="dashboard-state compact"><strong>No linked opportunity</strong><span>This signal remains evidence only.</span></div>:<div className="commerce-list">{opportunities.data.map((item)=><Link href={`/opportunities/${item.opportunity_id}?kind=market`} key={item.link_id}><div><strong>{item.opportunity.title}</strong><p>{item.opportunity.category} · {item.opportunity.market} · {item.opportunity.geography}</p></div><aside><b>{pct(item.opportunity.confidence_score)}</b><span>{item.opportunity.status}</span></aside></Link>)}</div>}</section><section className="boundary-panel"><p className="eyebrow">Authority boundary</p><h2>Evidence, not a business decision</h2><p>This record can support demand and Opportunity analysis. It cannot create a product, approve an investment, or trigger execution.</p></section></div>;
}
