import Link from "next/link";
import type { ReactNode } from "react";

import type { ShopifyPublication, ShopifyReadiness, ShopifyWorkspace as Workspace } from "../lib/api/shopify";
import type { ApiResult } from "../lib/api/types";
import { PublicationAuthorizationAction, PublicationExecutionAction, PublicationRequestAction } from "./ShopifyActions";

const label=(value:string)=>value.replaceAll("_"," ");
const operationalLabel=(value:string)=>({not_configured:"NOT CONFIGURED",configured:"READY FOR CONNECTION",ready:"READY",requested:"AWAITING DECISION",authorized:"AUTHORIZED",pending:"QUEUED",queued:"QUEUED",processing:"EXECUTING",executing:"EXECUTING",published:"SUCCEEDED",succeeded:"SUCCEEDED",failed:"FAILED",in_sync:"IN SYNC",commerce_os_newer:"COMMERCE OS NEWER",shopify_changed_externally:"EXTERNAL DRIFT",missing_external_resource:"MANUAL INTERVENTION REQUIRED"}[value]??label(value).toUpperCase());
export function ShopifyControlCenter({result}:{result:ApiResult<Workspace>}){
 if(!result.ok)return <div className="dashboard-state state-error"><strong>Shopify workspace unavailable</strong><span>{result.error.message}</span></div>;
 const {connections,products,publications,resources,reconciliations,executions}=result.data;
 return <div className="commerce-workspace shopify-workspace">
  <section className="page-heading"><div><p className="eyebrow">Approved Listing → governed channel execution</p><h1>Shopify Control Center</h1><p className="page-description">Commerce OS remains source of truth. Shopify is an external draft execution channel with separate authorization, explicit execution, and reconciliation.</p></div><div className="live-contract"><span>Real connection</span><strong>{connections.length?label(connections[0].status):"SHOPIFY NOT CONFIGURED"}</strong></div></section>
  <section className="intelligence-metrics"><Metric name="Connections" value={connections.length}/><Metric name="Publication ready" value={products.filter(x=>x.status==="ready").length}/><Metric name="Authorized / queued" value={publications.filter(x=>["authorized","queued"].includes(x.status)).length}/><Metric name="External resources" value={resources.length}/></section>
  {!connections.length?<section className="boundary-panel"><p className="eyebrow">Configuration state — not a system failure</p><h2>NOT CONFIGURED</h2><p>Mock acceptance remains available without a merchant store. A future real connection must use a server-only credential reference; never paste a token into the browser or source code.</p></section>:<section className="commerce-panel"><header><div><p className="eyebrow">Tenant-scoped connection</p><h2>{connections[0].display_name}</h2></div><strong>{operationalLabel(connections[0].status)}</strong></header><div className="shopify-facts"><Fact name="Store" value={connections[0].store_domain}/><Fact name="Merchant identity" value={connections[0].merchant_name??"Not validated"}/><Fact name="Store plan" value={connections[0].plan_display_name??"Unknown"}/><Fact name="API" value={`GraphQL Admin ${connections[0].api_version}`}/><Fact name="Required scopes" value={connections[0].required_scopes.join(", ")}/><Fact name="Granted scopes" value={connections[0].granted_scopes.join(", ")||"UNKNOWN"}/><Fact name="Credential" value={connections[0].credential_configured?"Server reference configured":"Not configured"}/></div></section>}
  <section className="product-catalog">{products.map(item=><Link href={`/channels/shopify/${item.product_id}`} key={item.product_id}><div className="product-catalog-main"><span>Product Truth v{item.product_truth_version??"UNKNOWN"} · Listing v{item.listing_version??"UNKNOWN"}</span><h2>{item.projection?.title??`Product ${item.product_id}`}</h2><p>{item.next_action}</p><small>{item.operation.toUpperCase()} · drift {label(item.drift_status)}</small></div><div className="product-catalog-facts"><div><span>Readiness</span><strong>{label(item.status)}</strong></div><div><span>Authorization</span><strong>{label(item.authorization_status)}</strong></div><div><span>Publication</span><strong>{label(item.publication_status)}</strong></div><div><span>Media</span><strong>{label(item.media_status)}</strong></div></div><aside><b>{item.blockers.length} blockers</b><span>Open Shopify →</span></aside></Link>)}</section>
  <section className="commerce-grid commerce-grid-wide"><Panel title="Execution queue" eyebrow="Durable Outbox → Worker">{executions.length?executions.map(item=><div className="listing-content-row" key={item.outbox_id}><span>{operationalLabel(item.status)}</span><p>{item.attempts} attempt(s){item.last_error?` · ${item.last_error}`:""}</p></div>):<p className="panel-footnote">No Shopify execution has been queued.</p>}</Panel><Panel title="Reconciliation" eyebrow="Human-visible external state"><h2>{reconciliations[0]?operationalLabel(reconciliations[0].status):"NOT RUN"}</h2><p>External drift and missing resources require manual intervention; Commerce OS never silently overwrites them.</p></Panel></section>
  <section className="boundary-panel"><p className="eyebrow">Monitoring</p><h2>{reconciliations[0]?operationalLabel(reconciliations[0].status):"No reconciliation yet"}</h2><p>SUCCEEDED means a successful external execution record exists. It does not mean the product is published to a sales channel.</p><strong>PUBLICATION APPROVAL ≠ EXTERNAL EXECUTION ≠ AD AUTHORITY</strong></section>
 </div>
}

export function ShopifyProductDetail({item,connection,publication,execution}:{item:ShopifyReadiness;connection:Workspace["connections"][number]|null;publication:ShopifyPublication|null;execution:Workspace["executions"][number]|null}){
 const projection=item.projection;
 return <div className="commerce-workspace shopify-workspace"><Link className="back-link" href="/channels/shopify">← Shopify Control Center</Link>
 <section className="commerce-hero"><div><p className="eyebrow">Governed Shopify draft channel</p><h1>{projection?.title??"Shopify publication workspace"}</h1><p>{item.next_action}</p><div className="opportunity-tags"><span>{item.status}</span><span>{item.operation}</span><span>{label(item.drift_status)}</span></div></div><aside><span>External state</span><strong>→</strong><small>{item.external_product_id??"No Shopify Product ID"}</small></aside></section>
 <section className="commerce-grid commerce-grid-wide"><Panel title="Connection" eyebrow="Server-only credentials"><Fact name="Status" value={connection?.status??"SHOPIFY NOT CONFIGURED"}/><Fact name="Store" value={connection?.store_domain??"UNKNOWN"}/><Fact name="Required scopes" value={connection?.required_scopes.join(", ")??"read_products, write_products"}/><Fact name="API version" value={connection?.api_version??"2026-07"}/></Panel><Panel title="Pinned source truth" eyebrow="Exact versions"><Fact name="Product" value={item.product_id}/><Fact name="Product Truth" value={`${item.product_truth_id??"UNKNOWN"} · v${item.product_truth_version??"—"}`}/><Fact name="Approved Listing" value={`${item.listing_version_id??"UNKNOWN"} · v${item.listing_version??"—"}`}/><Fact name="Projection hash" value={item.projection_hash??"UNKNOWN"}/></Panel></section>
 <section className="commerce-grid commerce-grid-wide"><Panel title="Shopify Projection" eyebrow="Draft · no inventory assumptions"><Fact name="Title" value={projection?.title??"UNKNOWN"}/><Fact name="Vendor" value={projection?.vendor??"UNKNOWN"}/><Fact name="Product type" value={projection?.product_type??"UNKNOWN"}/><Fact name="Variants" value={String(projection?.variants.length??0)}/><Fact name="Media" value={String(projection?.media.length??0)}/><Fact name="Inventory quantities" value="NONE — never fabricated"/></Panel><Panel title="Publication Readiness" eyebrow="Backend-owned"><div className="readiness-list">{item.blockers.map(x=><article className="readiness-blocker" key={x.code}><span>BLOCKER</span><strong>{label(x.code)}</strong><p>{x.message}</p></article>)}{item.warnings.map(x=><article className="readiness-warning" key={x.code}><span>WARNING — non-blocking</span><strong>{label(x.code)}</strong><p>{x.message}</p></article>)}</div><p className="panel-footnote"><strong>{item.status.toUpperCase()}</strong></p></Panel></section>
 <section className="commerce-grid commerce-grid-wide"><Panel title="Governance" eyebrow="Separate authority and execution"><Fact name="Request" value={publication?.id??"Not requested"}/><Fact name="Approval" value={publication?.approval_request_id??"Not requested"}/><Fact name="Authorization" value={operationalLabel(publication?.status??"not_configured")}/>{!publication&&connection&&item.status!=="not_ready"?<PublicationRequestAction productId={item.product_id} connectionId={connection.id}/>:null}{publication?.status==="requested"&&publication.approval_request_id?<><Link href={`/channels/shopify/publications/${publication.id}`}>Open publication decision →</Link><PublicationAuthorizationAction productId={item.product_id} publicationId={publication.id} approvalId={publication.approval_request_id}/></>:null}{publication?.status==="authorized"?<PublicationExecutionAction productId={item.product_id} publicationId={publication.id}/>:null}</Panel><Panel title="Execution & Reconciliation" eyebrow="No silent external mutation"><Fact name="Operation" value={item.operation}/><Fact name="Execution" value={execution?operationalLabel(execution.status):"NOT QUEUED"}/><Fact name="External Product ID" value={item.external_product_id??"NONE"}/><Fact name="External status" value={operationalLabel(item.publication_status)}/><Fact name="Drift" value={operationalLabel(item.drift_status)}/><p className="panel-footnote">A newer Listing requires a new authorization. External drift requires human review; no automatic overwrite occurs.</p></Panel></section>
 <section className="boundary-panel"><p className="eyebrow">Authority boundary</p><h2>Shopify Product remains a safe draft</h2><p>Successful execution creates or updates only the linked external draft resource. It does not invent inventory, publish to a sales channel, launch advertising, or create customer acquisition.</p><strong>APPROVAL ≠ EXECUTION · EXECUTION ≠ TRAFFIC</strong></section></div>
}
function Panel({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <section className="commerce-panel"><header><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></header>{children}</section>}
function Fact({name,value}:{name:string;value:string}){return <div className="listing-content-row"><span>{name}</span><p>{value}</p></div>}
function Metric({name,value}:{name:string;value:number}){return <article><span>{name}</span><strong>{value}</strong><small>governed state</small></article>}
