"use client";

import { useActionState } from "react";
import { authorizeShopifyPublication, executeShopifyPublication, requestShopifyPublication, type ShopifyActionState } from "../app/channels/shopify/actions";

const initial:ShopifyActionState={kind:"idle",message:""};
function Message({state}:{state:ShopifyActionState}){return state.message?<p className={state.kind==="error"?"inline-alert":"panel-footnote"}>{state.message}</p>:null;}
export function PublicationRequestAction({productId,connectionId}:{productId:string;connectionId:string}){const [state,action,pending]=useActionState(requestShopifyPublication,initial);return <form action={action} className="shopify-action"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="connection_id" value={connectionId}/><label>Publication reason<textarea name="reason" required minLength={3} placeholder="Why this exact approved Listing should become a safe Shopify draft."/></label><button className="primary-button" disabled={pending}>{pending?"Requesting…":"Request Shopify publication review"}</button><Message state={state}/></form>}
export function PublicationAuthorizationAction({productId,publicationId,approvalId}:{productId:string;publicationId:string;approvalId:string}){const [state,action,pending]=useActionState(authorizeShopifyPublication,initial);return <form action={action} className="shopify-action"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="publication_id" value={publicationId}/><input type="hidden" name="approval_request_id" value={approvalId}/><button className="primary-button" disabled={pending}>{pending?"Checking…":"Finalize approved authorization"}</button><Message state={state}/></form>}
export function PublicationExecutionAction({productId,publicationId}:{productId:string;publicationId:string}){const [state,action,pending]=useActionState(executeShopifyPublication,initial);return <form action={action} className="shopify-action"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="publication_id" value={publicationId}/><button className="danger-button" disabled={pending}>{pending?"Queueing…":"Execute authorized draft publication"}</button><p className="panel-footnote">This explicit action queues an idempotent Worker command. It never launches ads or invents inventory.</p><Message state={state}/></form>}
