import Link from "next/link";
import type { SupplierDetail } from "../lib/api/suppliers";
import { SupplierGovernanceAction } from "./SupplierGovernanceAction";

const label=(value:string)=>value.replaceAll("_"," ");
export function SupplierDetailWorkspace({detail}:{detail:SupplierDetail}){
  const {supplier}=detail;
  return <div className="commerce-workspace supplier-workspace"><Link className="back-link" href="/suppliers">← Supplier Intelligence</Link>
    <section className="commerce-hero"><div><p className="eyebrow">{supplier.source_type} · {supplier.country}</p><h1>{supplier.name}</h1><p>{supplier.capabilities.join(" · ")||"Capability evidence has not been recorded."}</p><div className="opportunity-tags"><span>{supplier.status}</span>{supplier.certifications.map(item=><span key={item}>{item}</span>)}</div></div><aside><span>Next governed action</span><strong>→</strong><small>{detail.next_action}</small></aside></section>
    {detail.qualifications.map(item=><section className="commerce-panel" key={item.product_id}><header><div><p className="eyebrow">Product {item.product_id}</p><h2>Qualification dashboard</h2></div><span>{item.ready?"READY FOR REVIEW":"GAPS REMAIN"}</span></header><div className="qualification-grid">{item.dimensions.map(d=><article key={d.dimension} className={`qualification-${d.status}`}><header><span>{label(d.dimension)}</span><b>{d.status}</b></header><strong>{d.confidence===null?"—":`${Math.round(d.confidence*100)}%`}</strong><p>{d.evidence.length?`${d.evidence.length} evidence record(s)`:d.gaps[0]}</p></article>)}</div><p className="panel-footnote"><strong>Next:</strong> {item.next_action}</p></section>)}
    <section className="commerce-grid commerce-grid-wide"><section className="commerce-panel"><header><div><p className="eyebrow">Traceable facts</p><h2>Evidence & provenance</h2></div><span>{detail.evidence.length}</span></header><div className="evidence-compact">{detail.evidence.map(item=><article key={item.id}><span>{item.classification}</span><p><strong>{label(item.field_name)}</strong><br/>{typeof item.value==="string"?item.value:JSON.stringify(item.value)}</p><b>{item.source}</b></article>)}</div></section><section className="commerce-panel"><header><div><p className="eyebrow">Commercial evidence</p><h2>Supplier quotes</h2></div><span>{detail.quotes.length}</span></header><div className="economic-ledger">{detail.quotes.map(item=><article key={item.id}><span>{item.classification}</span><strong>{item.unit_price===null?"UNKNOWN":`${item.currency} ${item.unit_price}`}</strong><small>MOQ {item.minimum_order_quantity??"UNKNOWN"} · {item.incoterm??"terms unknown"}</small><small>Sample {item.sample_cost??"UNKNOWN"} · Tooling {item.tooling_cost??"UNKNOWN"} · Packaging {item.packaging_cost??"UNKNOWN"}</small><small>{item.lead_time??"Lead time UNKNOWN"} · {item.payment_terms??"Payment terms UNKNOWN"}</small></article>)}</div></section></section>
    <section className="commerce-grid"><section className="commerce-panel"><header><div><p className="eyebrow">Product links</p><h2>Linked Products</h2></div><span>{detail.products.length}</span></header><div className="evidence-compact">{detail.products.map(item=><article key={item.id}><span>{item.recommended?"recommended":"candidate"}</span><p><strong>Product {item.product_id}</strong><br/>{item.reason}</p><b>{Math.round(item.match_score)} fit</b></article>)}</div></section><section className="commerce-panel"><header><div><p className="eyebrow">Evidence-backed warnings</p><h2>Supplier risks</h2></div><span>{detail.risks.length}</span></header><div className="risk-list">{detail.risks.length?detail.risks.map(item=><article key={item.id}><span className={`priority-mark priority-${item.severity}`}>{item.severity}</span><div><strong>{label(item.risk_type)}</strong><p>{item.description}</p><small>{item.status}</small></div></article>):<div className="dashboard-state compact"><strong>UNKNOWN</strong><span>No supplier risk record exists; this is not proof of zero risk.</span></div>}</div></section></section>
    <section className="commerce-panel"><header><div><p className="eyebrow">Authority boundary</p><h2>Selection status</h2></div></header><div className="evidence-compact">{detail.approved_relationships.length?detail.approved_relationships.map(item=><article key={item.id}><span>{item.role}</span><p>Product {item.product_id}</p><b>{item.status}</b></article>):<p className="panel-footnote">No governed Product-Supplier selection exists. Complete qualification, request approval, then decide it in Decision Committee.</p>}</div></section>
    {detail.qualifications[0]&&<SupplierGovernanceAction supplierId={supplier.id} productId={detail.qualifications[0].product_id} ready={detail.qualifications[0].ready}/>}
  </div>
}
