import Link from "next/link";
import type { ApiResult } from "../lib/api/types";
import type { ApprovedRelationship, Supplier, SupplierEvidence, SupplierMatch, SupplierQuote } from "../lib/api/suppliers";

export function SupplierIntelligenceWorkspace({suppliers,matches,quotes,evidence,relationships}:{suppliers:ApiResult<Supplier[]>;matches:ApiResult<SupplierMatch[]>;quotes:ApiResult<SupplierQuote[]>;evidence:ApiResult<SupplierEvidence[]>;relationships:ApiResult<ApprovedRelationship[]>}){
  const rows=suppliers.ok?suppliers.data:[];
  return <div className="commerce-workspace supplier-workspace">
    <section className="page-heading"><div><p className="eyebrow">Product Truth → qualification → governed selection</p><h1>Supplier Intelligence</h1><p className="page-description">Compare evidence, quotes, risks, and qualification gaps. Approval selects a supplier for a Product; it never authorizes purchasing or payment.</p></div><div className="live-contract"><span>Authority</span><strong>Governance review required</strong></div></section>
    <section className="intelligence-metrics"><article><span>Suppliers</span><strong>{rows.length}</strong><small>canonical profiles</small></article><article><span>Product matches</span><strong>{matches.ok?matches.data.length:"—"}</strong><small>many suppliers supported</small></article><article><span>Quotes</span><strong>{quotes.ok?quotes.data.length:"—"}</strong><small>provenance-bearing inputs</small></article><article><span>Approved relationships</span><strong>{relationships.ok?relationships.data.filter(x=>x.status==="approved").length:"—"}</strong><small>selection only · no purchase</small></article></section>
    {!suppliers.ok?<div className="dashboard-state state-error">{suppliers.error.message}</div>:!rows.length?<div className="dashboard-state"><strong>No supplier profiles yet</strong><span>Add evidence-backed supplier profiles before qualification.</span></div>:<section className="supplier-grid">{rows.map(supplier=>{const supplierMatches=matches.ok?matches.data.filter(x=>x.supplier_id===supplier.id):[];const supplierQuotes=quotes.ok?quotes.data.filter(x=>x.supplier_id===supplier.id):[];const supplierEvidence=evidence.ok?evidence.data.filter(x=>x.supplier_id===supplier.id):[];return <Link key={supplier.id} href={`/suppliers/${supplier.id}`}><header><span>{supplier.country}</span><b>{supplier.status}</b></header><h2>{supplier.name}</h2><p>{supplier.capabilities.join(" · ")||"Capabilities not evidenced"}</p><dl><div><dt>Products</dt><dd>{supplierMatches.length}</dd></div><div><dt>Quotes</dt><dd>{supplierQuotes.length}</dd></div><div><dt>Evidence</dt><dd>{supplierEvidence.length}</dd></div></dl><strong>Review qualification →</strong></Link>})}</section>}
  </div>
}
