"""Import all owned persistence models for metadata and migrations."""

from commerce_os.ai_runtime.models import (
    AICostObservation,
    AIModelCapability,
    AIProvider,
    AIRequest,
    PromptEvaluation,
    PromptPurpose,
    PromptTemplate,
    PromptVersion,
)
from commerce_os.build.creative_asset_models import (
    CreativeAsset,
    CreativeAssetVersion,
    CreativePerformanceObservation,
)
from commerce_os.build.creative_execution_models import (
    CreativeArtifact,
    CreativeExecutionRecord,
    CreativeGenerationCostObservation,
)
from commerce_os.build.creative_generation_models import (
    CreativeGenerationJob,
    CreativeGenerationRequest,
    CreativeProviderCapability,
    CreativeQualityReview,
)
from commerce_os.build.creative_production_models import (
    CreativeProductionAIProvenance,
    CreativeProductionRequest,
    CreativeProductionWork,
)
from commerce_os.build.listing_models import (
    ContentBrief,
    CustomerQuestion,
    ListingEvidence,
    ListingStrategy,
    ProductDiscoveryKnowledge,
)
from commerce_os.build.models import Product, ProductClaimPolicy, ProductKnowledgeItem, ProductTruth
from commerce_os.decision.cfo_models import CFOInsight
from commerce_os.decision.channel_models import (
    ChannelCandidate,
    ChannelDecisionEvidence,
    ChannelMeasurementPlan,
    ChannelOpportunityScore,
    ChannelStrategy,
    ConversionPath,
    ConversionPathStep,
)
from commerce_os.decision.creative_models import (
    CreativeBrief,
    CreativeChannelFit,
    CreativeExperiment,
    CreativeHypothesis,
    CreativeStrategy,
)
from commerce_os.decision.creative_router_models import (
    CreativeAssetStrategy,
    CreativeEconomicAssessment,
    CreativeModelProvider,
    CreativePatternReference,
    CreativeRoutingDecision,
)
from commerce_os.decision.customer_value_models import CustomerValueAssessment
from commerce_os.decision.discovery_listing_models import (
    AIDiscoveryReadinessAssessment,
    GeoKnowledgeAsset,
    ListingBlueprint,
    ListingQualityAssessment,
)
from commerce_os.decision.executive_models import (
    ExecutiveMetricSnapshot,
    OperatingCommitteeReview,
    OperatingSignal,
)
from commerce_os.decision.launch_models import (
    LaunchPreparationPackage,
    OfferStrategy,
    ProductObjectionMap,
    ProductPositioning,
)
from commerce_os.decision.models import VentureOpportunity
from commerce_os.decision.sales_support_models import (
    CustomerRiskSignal,
    SalesIntelligenceProfile,
    SalesRecommendation,
    SupportCaseIntelligence,
)
from commerce_os.decision.strategic_account_models import (
    CustomerExpansionOpportunity,
    CustomerNextBestAction,
    StrategicAccountScore,
)
from commerce_os.finance.models import (
    ContributionProfitAssessment,
    CostObservation,
    FinancialPeriod,
    FinancialRiskSignal,
    RevenueObservation,
    UnitEconomicAssessment,
)
from commerce_os.governance.executive_models import DecisionQueueItem
from commerce_os.governance.models import (
    AIActionPolicy,
    Approval,
    ApprovalRequest,
    AuditLog,
    AuthSession,
    CommercialPolicy,
    CustomerIdentity,
    Organization,
    PasswordCredential,
    Permission,
    Project,
    Role,
    RolePermission,
    User,
    UserRole,
)
from commerce_os.growth.channel_execution_models import (
    ChannelExecutionPlan,
    ChannelPerformanceObservation,
    CreativeChannelExperiment,
    DistributionRecord,
)
from commerce_os.growth.experiment_models import (
    DistributionCampaign,
    ExperimentVariant,
    GrowthCreativeExperiment,
    GrowthLearningObservationLink,
    GrowthLearningSignal,
    GrowthPerformanceObservation,
)
from commerce_os.intelligence.analysis_models import (
    MarketSignalAnalysis,
    OpportunityAssessment,
    OpportunityReport,
)
from commerce_os.intelligence.commercial_risk_models import (
    CommercialViabilityAssessment,
    ProductRiskAssessment,
    ProductRiskSignal,
)
from commerce_os.intelligence.connector_models import (
    CustomerPainCandidate,
    MarketConnectorDefinition,
    MarketDataRecord,
    MarketIngestionJob,
    NormalizedMarketItem,
    PainEvidence,
    RedditConnector,
)
from commerce_os.intelligence.customer_360_models import Customer360Profile, CustomerJourneyEvent
from commerce_os.intelligence.economics_models import (
    ProductEconomicProfile,
    ProductProfitAssessment,
    ProfitScenarioAssessment,
    RiskAdjustedProfitAssessment,
)
from commerce_os.intelligence.market_models import (
    MarketDataSource,
    MarketSignal,
    MarketSignalCluster,
    MarketSignalClusterMembership,
    MarketSignalEvidence,
    MarketSignalOpportunityLink,
)
from commerce_os.intelligence.marketplace_models import (
    CompetitiveMarketplaceObservation,
    MarketplaceEvidenceLink,
    MarketplaceReviewEvidence,
    NormalizedMarketplaceReview,
)
from commerce_os.intelligence.models import (
    CustomerInsight,
    CustomerSignal,
    CustomerVoiceCluster,
    InsightEvidence,
    SignalClusterMembership,
    SignalSource,
)
from commerce_os.intelligence.need_models import (
    CustomerBackedOpportunityAssessment,
    CustomerNeed,
    PainNeedMapping,
    ProductSolutionHypothesis,
)
from commerce_os.intelligence.opportunity_models import (
    MarketOpportunity,
    OpportunityEvidence,
    OpportunityRisk,
    OpportunityScore,
    ProductCandidate,
)
from commerce_os.intelligence.product_models import (
    ProductEconomics,
    ProductHypothesis,
    ProductInvestmentScore,
    ProductRisk,
    SupplierCandidate,
)
from commerce_os.intelligence.replenishment_models import ReplenishmentAssessment
from commerce_os.intelligence.research_models import (
    CustomerPainResearch,
    MarketInsightResearch,
    OpportunityResearchBrief,
    ResearchAnalysis,
    ResearchEvidenceCitation,
    ResearchRun,
    ResearchRunEvidence,
)
from commerce_os.intelligence.revenue_conversation_models import (
    CustomerIntentJourney,
    SalesIntentSignal,
    SupportLearningSignal,
)
from commerce_os.intelligence.supplier_models import (
    ProductSupplierMatch,
    SupplierDecisionRecord,
    SupplierEvaluation,
    SupplierProfile,
    SupplierRisk,
)
from commerce_os.intelligence.voice_models import (
    CustomerLanguageInsight,
    CustomerPainCluster,
    PainClusterMembership,
    PurchaseIntentSignal,
)
from commerce_os.learning.models import (
    ImprovementRecommendation,
    LearningConclusion,
    LearningObservation,
    RecommendationPriorityAssessment,
    RootCauseEvidenceLink,
    RootCauseHypothesis,
)
from commerce_os.operations.conversation_models import (
    ConversationEmotionSignal,
    ConversationHandoff,
    ConversationIntent,
    ConversationKnowledgeReference,
    ConversationMessage,
    ConversationThread,
)
from commerce_os.operations.customer_identity_models import CustomerIdentityLink
from commerce_os.operations.execution_models import (
    ActionPlan,
    ExecutionBlocker,
    ExecutionTask,
    LaunchMilestone,
    ProductLaunch,
)
from commerce_os.operations.models import (
    Brand,
    Conversation,
    Customer,
    MessageMetadata,
    SalesOpportunity,
    Store,
)
from commerce_os.operations.strategic_account_models import (
    AccountStakeholder,
    StrategicAccountProfile,
)
from commerce_os.shared.outbox import OutboxEvent

__all__ = [
    "AICostObservation",
    "AIModelCapability",
    "AIProvider",
    "AIRequest",
    "CreativeAsset",
    "CreativeAssetVersion",
    "CreativePerformanceObservation",
    "CreativeGenerationJob",
    "CreativeGenerationRequest",
    "CreativeProviderCapability",
    "CreativeQualityReview",
    "CreativeProductionRequest",
    "CreativeProductionWork",
    "CreativeProductionAIProvenance",
    "CreativeArtifact",
    "CreativeExecutionRecord",
    "CreativeGenerationCostObservation",
    "AIDiscoveryReadinessAssessment",
    "GeoKnowledgeAsset",
    "ListingBlueprint",
    "ListingQualityAssessment",
    "LaunchPreparationPackage",
    "OfferStrategy",
    "ProductObjectionMap",
    "ProductPositioning",
    "ProductEconomicProfile",
    "ProductProfitAssessment",
    "ProfitScenarioAssessment",
    "RiskAdjustedProfitAssessment",
    "CommercialViabilityAssessment",
    "ProductRiskAssessment",
    "ProductRiskSignal",
    "Approval",
    "ContentBrief",
    "CustomerQuestion",
    "ListingEvidence",
    "ListingStrategy",
    "Product",
    "ProductClaimPolicy",
    "ProductKnowledgeItem",
    "ProductDiscoveryKnowledge",
    "ProductTruth",
    "ApprovalRequest",
    "AuthSession",
    "ChannelExecutionPlan",
    "ChannelPerformanceObservation",
    "CreativeChannelExperiment",
    "DistributionRecord",
    "DistributionCampaign",
    "ExperimentVariant",
    "GrowthCreativeExperiment",
    "GrowthLearningObservationLink",
    "GrowthLearningSignal",
    "GrowthPerformanceObservation",
    "ImprovementRecommendation",
    "LearningConclusion",
    "LearningObservation",
    "RecommendationPriorityAssessment",
    "RootCauseEvidenceLink",
    "RootCauseHypothesis",
    "AuditLog",
    "Brand",
    "CommercialPolicy",
    "Conversation",
    "ConversationEmotionSignal",
    "ConversationHandoff",
    "ConversationIntent",
    "ConversationKnowledgeReference",
    "ConversationMessage",
    "ConversationThread",
    "Customer",
    "CustomerIdentity",
    "CustomerIdentityLink",
    "CustomerJourneyEvent",
    "CustomerIntentJourney",
    "Customer360Profile",
    "CustomerValueAssessment",
    "SalesIntentSignal",
    "SupportLearningSignal",
    "StrategicAccountProfile",
    "AccountStakeholder",
    "ReplenishmentAssessment",
    "CustomerExpansionOpportunity",
    "CustomerNextBestAction",
    "StrategicAccountScore",
    "AIActionPolicy",
    "CreativeBrief",
    "CreativeChannelFit",
    "CreativeExperiment",
    "CreativeHypothesis",
    "CreativeStrategy",
    "CFOInsight",
    "ExecutiveMetricSnapshot",
    "OperatingCommitteeReview",
    "OperatingSignal",
    "DecisionQueueItem",
    "CreativeAssetStrategy",
    "CreativeEconomicAssessment",
    "CreativeModelProvider",
    "CreativePatternReference",
    "CreativeRoutingDecision",
    "ChannelCandidate",
    "ChannelDecisionEvidence",
    "ChannelMeasurementPlan",
    "ChannelOpportunityScore",
    "ChannelStrategy",
    "ConversionPath",
    "ConversionPathStep",
    "MessageMetadata",
    "Organization",
    "OutboxEvent",
    "PasswordCredential",
    "Permission",
    "Project",
    "Role",
    "RolePermission",
    "SalesOpportunity",
    "Store",
    "User",
    "UserRole",
    "CustomerInsight",
    "CustomerBackedOpportunityAssessment",
    "CustomerNeed",
    "PainNeedMapping",
    "ProductSolutionHypothesis",
    "CustomerSignal",
    "CustomerVoiceCluster",
    "InsightEvidence",
    "SignalClusterMembership",
    "SignalSource",
    "MarketOpportunity",
    "OpportunityEvidence",
    "OpportunityRisk",
    "OpportunityScore",
    "ProductCandidate",
    "ProductEconomics",
    "ProductHypothesis",
    "ProductInvestmentScore",
    "ProductRisk",
    "SupplierCandidate",
    "SupplierProfile",
    "SupplierEvaluation",
    "SupplierRisk",
    "ProductSupplierMatch",
    "SupplierDecisionRecord",
    "VentureOpportunity",
    "ContributionProfitAssessment",
    "CostObservation",
    "FinancialPeriod",
    "FinancialRiskSignal",
    "RevenueObservation",
    "UnitEconomicAssessment",
    "CustomerRiskSignal",
    "SalesIntelligenceProfile",
    "SalesRecommendation",
    "SupportCaseIntelligence",
    "MarketDataSource",
    "CustomerPainCandidate",
    "MarketConnectorDefinition",
    "MarketDataRecord",
    "MarketIngestionJob",
    "MarketplaceReviewEvidence",
    "NormalizedMarketplaceReview",
    "MarketplaceEvidenceLink",
    "CompetitiveMarketplaceObservation",
    "NormalizedMarketItem",
    "PainEvidence",
    "RedditConnector",
    "MarketSignal",
    "MarketSignalCluster",
    "MarketSignalClusterMembership",
    "MarketSignalEvidence",
    "MarketSignalOpportunityLink",
    "MarketSignalAnalysis",
    "OpportunityAssessment",
    "OpportunityReport",
    "ActionPlan",
    "ExecutionBlocker",
    "ExecutionTask",
    "LaunchMilestone",
    "ProductLaunch",
    "CustomerLanguageInsight",
    "CustomerPainCluster",
    "PainClusterMembership",
    "PromptEvaluation",
    "PromptPurpose",
    "PromptTemplate",
    "PromptVersion",
    "PurchaseIntentSignal",
    "ResearchAnalysis",
    "ResearchEvidenceCitation",
    "ResearchRun",
    "ResearchRunEvidence",
    "CustomerPainResearch",
    "MarketInsightResearch",
    "OpportunityResearchBrief",
]
