"""Import all owned persistence models for metadata and migrations."""

from commerce_os.ai_runtime.models import (
    AICostObservation,
    AIModelCapability,
    AIProvider,
    AIRequest,
    PromptEvaluation,
    PromptPurpose,
    PromptTemplate,
    PromptVersion,
)
from commerce_os.build.creative_asset_models import (
    CreativeAsset,
    CreativeAssetVersion,
    CreativePerformanceObservation,
)
from commerce_os.build.creative_execution_models import (
    CreativeArtifact,
    CreativeExecutionRecord,
    CreativeGenerationCostObservation,
)
from commerce_os.build.creative_generation_models import (
    CreativeGenerationJob,
    CreativeGenerationRequest,
    CreativeProviderCapability,
    CreativeQualityReview,
)
from commerce_os.build.creative_production_models import (
    CreativeProductionAIProvenance,
    CreativeProductionRequest,
    CreativeProductionWork,
)
from commerce_os.build.listing_models import (
    ContentBrief,
    CustomerQuestion,
    ListingEvidence,
    ListingStrategy,
    ProductDiscoveryKnowledge,
)
from commerce_os.build.models import Product, ProductClaimPolicy, ProductKnowledgeItem, ProductTruth
from commerce_os.build.promotion_models import ProductPromotion, ProductTruthDraft
from commerce_os.decision.cfo_models import CFOInsight
from commerce_os.decision.channel_models import (
    ChannelCandidate,
    ChannelDecisionEvidence,
    ChannelMeasurementPlan,
    ChannelOpportunityScore,
    ChannelStrategy,
    ConversionPath,
    ConversionPathStep,
)
from commerce_os.decision.creative_intelligence_models import (
    CreativeAngle,
    CreativeBriefRecommendation,
    CreativeIntelligenceEvidence,
    CreativeIntelligenceRun,
    CreativeStrategyRecommendation,
)
from commerce_os.decision.creative_models import (
    CreativeBrief,
    CreativeChannelFit,
    CreativeExperiment,
    CreativeHypothesis,
    CreativeStrategy,
)
from commerce_os.decision.creative_router_models import (
    CreativeAssetStrategy,
    CreativeEconomicAssessment,
    CreativeModelProvider,
    CreativePatternReference,
    CreativeRoutingDecision,
)
from commerce_os.decision.customer_value_models import CustomerValueAssessment
from commerce_os.decision.discovery_listing_models import (
    AIDiscoveryReadinessAssessment,
    GeoKnowledgeAsset,
    ListingBlueprint,
    ListingQualityAssessment,
)
from commerce_os.decision.executive_models import (
    ExecutiveMetricSnapshot,
    OperatingCommitteeReview,
    OperatingSignal,
)
from commerce_os.decision.launch_models import (
    LaunchPreparationPackage,
    OfferStrategy,
    ProductObjectionMap,
    ProductPositioning,
)
from commerce_os.decision.listing_geo_intelligence_models import (
    FAQRecommendation,
    GEOContentRecommendation,
    ListingIntelligenceEvidence,
    ListingIntelligenceRun,
    ListingStrategyRecommendation,
)
from commerce_os.decision.models import VentureOpportunity
from commerce_os.decision.sales_support_models import (
    CustomerRiskSignal,
    SalesIntelligenceProfile,
    SalesRecommendation,
    SupportCaseIntelligence,
)
from commerce_os.decision.strategic_account_models import (
    CustomerExpansionOpportunity,
    CustomerNextBestAction,
    StrategicAccountScore,
)
from commerce_os.finance.models import (
    ContributionProfitAssessment,
    CostObservation,
    FinancialPeriod,
    FinancialRiskSignal,
    RevenueObservation,
    UnitEconomicAssessment,
)
from commerce_os.governance.executive_models import DecisionQueueItem
from commerce_os.governance.models import (
    AIActionPolicy,
    Approval,
    ApprovalRequest,
    AuditLog,
    AuthSession,
    CommercialPolicy,
    CustomerIdentity,
    Organization,
    PasswordCredential,
    Permission,
    Project,
    Role,
    RolePermission,
    User,
    UserRole,
)
from commerce_os.growth.activation_models import (
    ExperimentFeedbackSignal,
    OfferExperiment,
    OfferExperimentOutcome,
    OutreachTrackingEvent,
    ProspectExperimentLink,
    RevenueExperiment,
)
from commerce_os.growth.channel_execution_models import (
    ChannelExecutionPlan,
    ChannelPerformanceObservation,
    CreativeChannelExperiment,
    DistributionRecord,
)
from commerce_os.growth.conversation_learning_models import (
    GrowthMessagePerformanceObservation,
    GrowthObjectionRecord,
    GrowthSalesLearningSignal,
)
from commerce_os.growth.discovery_models import (
    BusinessProfileEvidenceSnapshot,
    DiscoveryAutomationPlan,
    GoogleBusinessDiscoveryResult,
    GrowthBusinessResearchResult,
    GrowthBusinessResearchRun,
    InstagramEvidenceSnapshot,
    ProspectCandidate,
    ProspectDiscoveryRun,
    ProspectDiscoverySource,
    ProspectMemoryEvent,
    ProspectQualificationAssessment,
    ProspectResearchEvidence,
    WebsiteEvidenceSnapshot,
)
from commerce_os.growth.experiment_models import (
    DistributionCampaign,
    ExperimentVariant,
    GrowthCreativeExperiment,
    GrowthLearningObservationLink,
    GrowthLearningSignal,
    GrowthPerformanceObservation,
)
from commerce_os.growth.industry_intelligence_models import (
    GrowthGEOAssessment,
    GrowthServiceRecommendation,
    IndustryGrowthEvidence,
    IndustryGrowthPattern,
    IndustryGrowthProfile,
    IndustryLearningSignal,
)
from commerce_os.growth.live_revenue_models import (
    CustomerDeliveryItem,
    CustomerServiceDelivery,
    DailyRevenueRun,
    DailyRevenueRunProspect,
    FounderActionItem,
    GrowthExternalDataConnector,
)
from commerce_os.growth.revenue_execution_models import DailyGrowthOpportunity
from commerce_os.growth.revenue_launch_models import (
    CustomerLifecycleEvent,
    PaymentReadinessRecord,
    ProspectRevenuePipeline,
    RevenueOfferTracking,
)
from commerce_os.growth.revenue_models import (
    AIModelPolicy,
    BusinessGrowthProfile,
    GrowthDiagnosis,
    GrowthGift,
    GrowthOfferRecommendation,
    GrowthOpportunityAnalysis,
    GrowthOutreachDraft,
    GrowthProspect,
    GrowthProspectEvidence,
    GrowthProspectRanking,
    IndustryDeliveryKnowledge,
    SalesConversationAnalysis,
)
from commerce_os.growth.revenue_operations_models import (
    DailyExperimentWorkspaceItem,
    EmailWorkflowReference,
    GrowthCustomerFeedback,
)
from commerce_os.intelligence.analysis_models import (
    MarketSignalAnalysis,
    OpportunityAssessment,
    OpportunityReport,
)
from commerce_os.intelligence.business_signal_models import BusinessDemandSignal
from commerce_os.intelligence.commercial_risk_models import (
    CommercialViabilityAssessment,
    ProductRiskAssessment,
    ProductRiskSignal,
)
from commerce_os.intelligence.connector_models import (
    CustomerPainCandidate,
    MarketConnectorDefinition,
    MarketDataRecord,
    MarketIngestionJob,
    NormalizedMarketItem,
    PainEvidence,
    RedditConnector,
)
from commerce_os.intelligence.customer_360_models import Customer360Profile, CustomerJourneyEvent
from commerce_os.intelligence.demand_bridge_models import (
    DemandSignal,
    DemandSignalEvidence,
    DemandSignalSource,
    DemandThemeAnalysis,
    DemandThemeSignalLink,
    PredictiveDemandMetadata,
)
from commerce_os.intelligence.discovery_models import (
    OpportunityCandidate,
    OpportunityCandidateAssessment,
    OpportunityCandidateEvidence,
    OpportunityDiscoveryEvidence,
    OpportunityDiscoveryRun,
)
from commerce_os.intelligence.economics_models import (
    ProductEconomicProfile,
    ProductProfitAssessment,
    ProfitScenarioAssessment,
    RiskAdjustedProfitAssessment,
)
from commerce_os.intelligence.market_models import (
    MarketDataSource,
    MarketSignal,
    MarketSignalCluster,
    MarketSignalClusterMembership,
    MarketSignalEvidence,
    MarketSignalOpportunityLink,
)
from commerce_os.intelligence.marketplace_models import (
    CompetitiveMarketplaceObservation,
    MarketplaceEvidenceLink,
    MarketplaceReviewEvidence,
    NormalizedMarketplaceReview,
)
from commerce_os.intelligence.models import (
    CustomerInsight,
    CustomerSignal,
    CustomerVoiceCluster,
    InsightEvidence,
    SignalClusterMembership,
    SignalSource,
)
from commerce_os.intelligence.need_models import (
    CustomerBackedOpportunityAssessment,
    CustomerNeed,
    PainNeedMapping,
    ProductSolutionHypothesis,
)
from commerce_os.intelligence.opportunity_models import (
    MarketOpportunity,
    OpportunityEvidence,
    OpportunityRisk,
    OpportunityScore,
    ProductCandidate,
    ProductCandidateEvidence,
    ProductEvaluation,
)
from commerce_os.intelligence.product_models import (
    ProductEconomicInputProvenance,  # noqa: F401
    ProductEconomics,
    ProductHypothesis,
    ProductInvestmentScore,
    ProductRisk,
    SupplierCandidate,
)
from commerce_os.intelligence.replenishment_models import ReplenishmentAssessment
from commerce_os.intelligence.research_models import (
    CustomerPainResearch,
    MarketInsightResearch,
    OpportunityResearchBrief,
    ResearchAnalysis,
    ResearchEvidenceCitation,
    ResearchRun,
    ResearchRunEvidence,
)
from commerce_os.intelligence.revenue_conversation_models import (
    CustomerIntentJourney,
    SalesIntentSignal,
    SupportLearningSignal,
)
from commerce_os.intelligence.supplier_models import (
    ProductSupplierMatch,
    SupplierDecisionRecord,
    SupplierEvaluation,
    SupplierProfile,
    SupplierRisk,
)
from commerce_os.intelligence.voice_models import (
    CustomerLanguageInsight,
    CustomerPainCluster,
    PainClusterMembership,
    PurchaseIntentSignal,
)
from commerce_os.learning.models import (
    ImprovementRecommendation,
    LearningConclusion,
    LearningObservation,
    RecommendationPriorityAssessment,
    RootCauseEvidenceLink,
    RootCauseHypothesis,
)
from commerce_os.operations.conversation_models import (
    ConversationEmotionSignal,
    ConversationHandoff,
    ConversationIntent,
    ConversationKnowledgeReference,
    ConversationMessage,
    ConversationThread,
)
from commerce_os.operations.customer_identity_models import CustomerIdentityLink
from commerce_os.operations.execution_models import (
    ActionPlan,
    ExecutionBlocker,
    ExecutionTask,
    LaunchMilestone,
    ProductLaunch,
)
from commerce_os.operations.models import (
    Brand,
    Conversation,
    Customer,
    MessageMetadata,
    SalesOpportunity,
    Store,
)
from commerce_os.operations.strategic_account_models import (
    AccountStakeholder,
    StrategicAccountProfile,
)
from commerce_os.shared.outbox import OutboxEvent

__all__ = [
    "AICostObservation",
    "AIModelCapability",
    "AIProvider",
    "AIRequest",
    "CreativeAsset",
    "CreativeAssetVersion",
    "CreativePerformanceObservation",
    "CreativeGenerationJob",
    "CreativeGenerationRequest",
    "CreativeProviderCapability",
    "CreativeQualityReview",
    "CreativeProductionRequest",
    "CreativeProductionWork",
    "CreativeProductionAIProvenance",
    "CreativeArtifact",
    "CreativeExecutionRecord",
    "CreativeGenerationCostObservation",
    "AIDiscoveryReadinessAssessment",
    "GeoKnowledgeAsset",
    "ListingBlueprint",
    "ListingQualityAssessment",
    "LaunchPreparationPackage",
    "OfferStrategy",
    "ProductObjectionMap",
    "ProductPositioning",
    "ProductEconomicProfile",
    "ProductProfitAssessment",
    "ProfitScenarioAssessment",
    "RiskAdjustedProfitAssessment",
    "CommercialViabilityAssessment",
    "ProductRiskAssessment",
    "ProductRiskSignal",
    "Approval",
    "ContentBrief",
    "CustomerQuestion",
    "ListingEvidence",
    "ListingStrategy",
    "Product",
    "ProductClaimPolicy",
    "ProductKnowledgeItem",
    "ProductDiscoveryKnowledge",
    "ProductTruth",
    "ProductPromotion",
    "ProductTruthDraft",
    "ApprovalRequest",
    "AuthSession",
    "ChannelExecutionPlan",
    "ChannelPerformanceObservation",
    "CreativeChannelExperiment",
    "DistributionRecord",
    "DistributionCampaign",
    "ExperimentVariant",
    "GrowthCreativeExperiment",
    "GrowthLearningObservationLink",
    "GrowthLearningSignal",
    "GrowthPerformanceObservation",
    "RevenueExperiment",
    "ProspectExperimentLink",
    "OutreachTrackingEvent",
    "GrowthObjectionRecord",
    "GrowthSalesLearningSignal",
    "GrowthMessagePerformanceObservation",
    "ProspectDiscoverySource",
    "ProspectDiscoveryRun",
    "ProspectCandidate",
    "ProspectResearchEvidence",
    "WebsiteEvidenceSnapshot",
    "BusinessProfileEvidenceSnapshot",
    "InstagramEvidenceSnapshot",
    "DiscoveryAutomationPlan",
    "GoogleBusinessDiscoveryResult",
    "ProspectMemoryEvent",
    "GrowthBusinessResearchRun",
    "GrowthBusinessResearchResult",
    "ProspectQualificationAssessment",
    "BusinessDemandSignal",
    "DemandSignal",
    "DemandSignalEvidence",
    "DemandSignalSource",
    "DemandThemeAnalysis",
    "DemandThemeSignalLink",
    "PredictiveDemandMetadata",
    "GrowthProspect",
    "GrowthProspectEvidence",
    "BusinessGrowthProfile",
    "GrowthProspectRanking",
    "GrowthOpportunityAnalysis",
    "GrowthDiagnosis",
    "GrowthOfferRecommendation",
    "ExperimentFeedbackSignal",
    "OfferExperiment",
    "OfferExperimentOutcome",
    "DailyGrowthOpportunity",
    "ProspectRevenuePipeline",
    "RevenueOfferTracking",
    "PaymentReadinessRecord",
    "CustomerLifecycleEvent",
    "DailyExperimentWorkspaceItem",
    "EmailWorkflowReference",
    "GrowthCustomerFeedback",
    "DailyRevenueRun",
    "DailyRevenueRunProspect",
    "FounderActionItem",
    "GrowthExternalDataConnector",
    "CustomerServiceDelivery",
    "CustomerDeliveryItem",
    "GrowthGEOAssessment",
    "GrowthServiceRecommendation",
    "IndustryGrowthEvidence",
    "IndustryGrowthPattern",
    "IndustryGrowthProfile",
    "IndustryLearningSignal",
    "GrowthGift",
    "GrowthOutreachDraft",
    "SalesConversationAnalysis",
    "IndustryDeliveryKnowledge",
    "AIModelPolicy",
    "ImprovementRecommendation",
    "LearningConclusion",
    "LearningObservation",
    "RecommendationPriorityAssessment",
    "RootCauseEvidenceLink",
    "RootCauseHypothesis",
    "AuditLog",
    "Brand",
    "CommercialPolicy",
    "Conversation",
    "ConversationEmotionSignal",
    "ConversationHandoff",
    "ConversationIntent",
    "ConversationKnowledgeReference",
    "ConversationMessage",
    "ConversationThread",
    "Customer",
    "CustomerIdentity",
    "CustomerIdentityLink",
    "CustomerJourneyEvent",
    "CustomerIntentJourney",
    "Customer360Profile",
    "CustomerValueAssessment",
    "SalesIntentSignal",
    "SupportLearningSignal",
    "StrategicAccountProfile",
    "AccountStakeholder",
    "ReplenishmentAssessment",
    "CustomerExpansionOpportunity",
    "CustomerNextBestAction",
    "StrategicAccountScore",
    "AIActionPolicy",
    "CreativeBrief",
    "CreativeChannelFit",
    "CreativeExperiment",
    "CreativeHypothesis",
    "CreativeStrategy",
    "CreativeAngle",
    "CreativeBriefRecommendation",
    "CreativeIntelligenceEvidence",
    "CreativeIntelligenceRun",
    "CreativeStrategyRecommendation",
    "FAQRecommendation",
    "GEOContentRecommendation",
    "ListingIntelligenceEvidence",
    "ListingIntelligenceRun",
    "ListingStrategyRecommendation",
    "CFOInsight",
    "ExecutiveMetricSnapshot",
    "OperatingCommitteeReview",
    "OperatingSignal",
    "DecisionQueueItem",
    "CreativeAssetStrategy",
    "CreativeEconomicAssessment",
    "CreativeModelProvider",
    "CreativePatternReference",
    "CreativeRoutingDecision",
    "ChannelCandidate",
    "ChannelDecisionEvidence",
    "ChannelMeasurementPlan",
    "ChannelOpportunityScore",
    "ChannelStrategy",
    "ConversionPath",
    "ConversionPathStep",
    "MessageMetadata",
    "Organization",
    "OutboxEvent",
    "PasswordCredential",
    "Permission",
    "Project",
    "Role",
    "RolePermission",
    "SalesOpportunity",
    "Store",
    "User",
    "UserRole",
    "CustomerInsight",
    "CustomerBackedOpportunityAssessment",
    "CustomerNeed",
    "PainNeedMapping",
    "ProductSolutionHypothesis",
    "CustomerSignal",
    "CustomerVoiceCluster",
    "InsightEvidence",
    "SignalClusterMembership",
    "SignalSource",
    "MarketOpportunity",
    "OpportunityEvidence",
    "OpportunityRisk",
    "OpportunityScore",
    "ProductCandidate",
    "ProductCandidateEvidence",
    "ProductEvaluation",
    "ProductEconomics",
    "ProductHypothesis",
    "ProductInvestmentScore",
    "ProductRisk",
    "SupplierCandidate",
    "SupplierProfile",
    "SupplierEvaluation",
    "SupplierRisk",
    "ProductSupplierMatch",
    "SupplierDecisionRecord",
    "VentureOpportunity",
    "ContributionProfitAssessment",
    "CostObservation",
    "FinancialPeriod",
    "FinancialRiskSignal",
    "RevenueObservation",
    "UnitEconomicAssessment",
    "CustomerRiskSignal",
    "SalesIntelligenceProfile",
    "SalesRecommendation",
    "SupportCaseIntelligence",
    "MarketDataSource",
    "CustomerPainCandidate",
    "MarketConnectorDefinition",
    "MarketDataRecord",
    "MarketIngestionJob",
    "MarketplaceReviewEvidence",
    "NormalizedMarketplaceReview",
    "MarketplaceEvidenceLink",
    "CompetitiveMarketplaceObservation",
    "NormalizedMarketItem",
    "PainEvidence",
    "RedditConnector",
    "MarketSignal",
    "MarketSignalCluster",
    "MarketSignalClusterMembership",
    "MarketSignalEvidence",
    "MarketSignalOpportunityLink",
    "MarketSignalAnalysis",
    "OpportunityAssessment",
    "OpportunityReport",
    "OpportunityCandidate",
    "OpportunityCandidateAssessment",
    "OpportunityCandidateEvidence",
    "OpportunityDiscoveryEvidence",
    "OpportunityDiscoveryRun",
    "ActionPlan",
    "ExecutionBlocker",
    "ExecutionTask",
    "LaunchMilestone",
    "ProductLaunch",
    "CustomerLanguageInsight",
    "CustomerPainCluster",
    "PainClusterMembership",
    "PromptEvaluation",
    "PromptPurpose",
    "PromptTemplate",
    "PromptVersion",
    "PurchaseIntentSignal",
    "ResearchAnalysis",
    "ResearchEvidenceCitation",
    "ResearchRun",
    "ResearchRunEvidence",
    "CustomerPainResearch",
    "MarketInsightResearch",
    "OpportunityResearchBrief",
]
