"""Import all owned persistence models for metadata and migrations."""

from commerce_os.build.listing_models import (
    ContentBrief,
    CustomerQuestion,
    ListingEvidence,
    ListingStrategy,
    ProductDiscoveryKnowledge,
)
from commerce_os.build.models import Product, ProductClaimPolicy, ProductKnowledgeItem, ProductTruth
from commerce_os.decision.models import VentureOpportunity
from commerce_os.governance.models import (
    Approval,
    ApprovalRequest,
    AuditLog,
    CommercialPolicy,
    CustomerIdentity,
    Organization,
    PasswordCredential,
    Permission,
    Project,
    Role,
    RolePermission,
    User,
    UserRole,
)
from commerce_os.intelligence.models import (
    CustomerInsight,
    CustomerSignal,
    CustomerVoiceCluster,
    InsightEvidence,
    SignalClusterMembership,
    SignalSource,
)
from commerce_os.intelligence.opportunity_models import (
    MarketOpportunity,
    OpportunityEvidence,
    OpportunityRisk,
    OpportunityScore,
    ProductCandidate,
)
from commerce_os.intelligence.product_models import (
    ProductEconomics,
    ProductHypothesis,
    ProductInvestmentScore,
    ProductRisk,
    SupplierCandidate,
)
from commerce_os.intelligence.supplier_models import (
    ProductSupplierMatch,
    SupplierDecisionRecord,
    SupplierEvaluation,
    SupplierProfile,
    SupplierRisk,
)
from commerce_os.operations.models import (
    Brand,
    Conversation,
    Customer,
    MessageMetadata,
    SalesOpportunity,
    Store,
)
from commerce_os.shared.outbox import OutboxEvent

__all__ = [
    "Approval",
    "ContentBrief",
    "CustomerQuestion",
    "ListingEvidence",
    "ListingStrategy",
    "Product",
    "ProductClaimPolicy",
    "ProductKnowledgeItem",
    "ProductDiscoveryKnowledge",
    "ProductTruth",
    "ApprovalRequest",
    "AuditLog",
    "Brand",
    "CommercialPolicy",
    "Conversation",
    "Customer",
    "CustomerIdentity",
    "MessageMetadata",
    "Organization",
    "OutboxEvent",
    "PasswordCredential",
    "Permission",
    "Project",
    "Role",
    "RolePermission",
    "SalesOpportunity",
    "Store",
    "User",
    "UserRole",
    "CustomerInsight",
    "CustomerSignal",
    "CustomerVoiceCluster",
    "InsightEvidence",
    "SignalClusterMembership",
    "SignalSource",
    "MarketOpportunity",
    "OpportunityEvidence",
    "OpportunityRisk",
    "OpportunityScore",
    "ProductCandidate",
    "ProductEconomics",
    "ProductHypothesis",
    "ProductInvestmentScore",
    "ProductRisk",
    "SupplierCandidate",
    "SupplierProfile",
    "SupplierEvaluation",
    "SupplierRisk",
    "ProductSupplierMatch",
    "SupplierDecisionRecord",
    "VentureOpportunity",
]
